global:
  projectName: ohp-telikos
  env: prod

# If you want to enable HPA [Only applicable in QA/PP/Prod]
k8sObjectsEnabled:
  hpa: true # By Default is Disabled[Enter Value in Boolean]

# If HPA not enabled it will use static replica count.
replicaCount: {} # you can increase as per application traffic, Default is 1

#+++++++++++++++++++++++++++++++++Developer Use++++++++++++++++++++++++++++++++++#
configMap:
  data:
    #TokenConfig
    FORGEROCK_ISS: vault:ohptelikos-kv/data/readable/prod/forgerock#iss
    FORGEROCK_KEYSTORE: vault:ohptelikos-kv/data/readable/prod/forgerock#keyStore
